#spring.application.name=pilotos
spring.datasource.url=jdbc:postgresql://localhost/pilotos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always
